set echo on
SPOOL oo_schema_output.txt

--student id: 34280332
--student name: Cheng Mun Chee


-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-05-01 19:26:04 MYT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



DROP TABLE BOOKING CASCADE CONSTRAINTS 
;

DROP TABLE CABIN CASCADE CONSTRAINTS 
;

DROP TABLE COUNTRY CASCADE CONSTRAINTS 
;

DROP TABLE CRUISE CASCADE CONSTRAINTS 
;

DROP TABLE CRUISE_PORT CASCADE CONSTRAINTS 
;

DROP TABLE OPERATOR CASCADE CONSTRAINTS 
;

DROP TABLE PASSENGER CASCADE CONSTRAINTS 
;

DROP TABLE PORT CASCADE CONSTRAINTS 
;

DROP TABLE SHIP CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE BOOKING 
    ( 
     booking_bordate DATE  NOT NULL , 
     pas_id          NUMBER (7)  NOT NULL , 
     cabin_no        NUMBER (7)  NOT NULL , 
     ship_code       NUMBER (7)  NOT NULL , 
     cruise_id       NUMBER (7)  NOT NULL , 
     booking_no      NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN BOOKING.booking_bordate IS 'Passenger Boarding date and time recorded in Booking' 
;

COMMENT ON COLUMN BOOKING.pas_id IS 'Passenger ID' 
;

COMMENT ON COLUMN BOOKING.cabin_no IS 'Cabin Number' 
;

COMMENT ON COLUMN BOOKING.ship_code IS 'Ship Code' 
;

COMMENT ON COLUMN BOOKING.cruise_id IS 'Cruise ID' 
;

COMMENT ON COLUMN BOOKING.booking_no IS 'Surrogate Key - Booking Number' 
;

ALTER TABLE BOOKING 
    ADD CONSTRAINT BOOKING_PK PRIMARY KEY ( booking_no ) ;

ALTER TABLE BOOKING 
    ADD CONSTRAINT BOOKING_NK UNIQUE ( pas_id , cruise_id ) ;

CREATE TABLE CABIN 
    ( 
     cabin_no       NUMBER (7)  NOT NULL , 
     cabin_class    CHAR (1)  NOT NULL , 
     cabin_capacity NUMBER (7)  NOT NULL , 
     ship_code      NUMBER (7)  NOT NULL 
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT chk_cabinclass 
    CHECK (cabin_class IN ('B', 'I', 'O', 'S')) 
;

COMMENT ON COLUMN CABIN.cabin_no IS 'Cabin Number' 
;

COMMENT ON COLUMN CABIN.cabin_class IS 'Cabin Class with constraint' 
;

COMMENT ON COLUMN CABIN.cabin_capacity IS 'Cabin Capacity' 
;

COMMENT ON COLUMN CABIN.ship_code IS 'Ship Code' 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT CABIN_PK PRIMARY KEY ( cabin_no, ship_code ) ;

CREATE TABLE COUNTRY 
    ( 
     country_code NUMBER (7)  NOT NULL , 
     country_name VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN COUNTRY.country_code IS 'Country Code' 
;

COMMENT ON COLUMN COUNTRY.country_name IS 'Country Name' 
;

ALTER TABLE COUNTRY 
    ADD CONSTRAINT COUNTRY_PK PRIMARY KEY ( country_code ) ;

CREATE TABLE CRUISE 
    ( 
     cruise_id      NUMBER (7)  NOT NULL , 
     cruise_name    VARCHAR2 (50)  NOT NULL , 
     cruise_desc    VARCHAR2 (50)  NOT NULL , 
     cruise_depdate DATE  NOT NULL , 
     ship_code      NUMBER (7)  NOT NULL , 
     cruise_cost    NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN CRUISE.cruise_id IS 'Cruise ID' 
;

COMMENT ON COLUMN CRUISE.cruise_name IS 'Cruise Name' 
;

COMMENT ON COLUMN CRUISE.cruise_desc IS 'Cruise Description' 
;

COMMENT ON COLUMN CRUISE.cruise_depdate IS 'Cruise Departure Date and Time' 
;

COMMENT ON COLUMN CRUISE.ship_code IS 'Ship Code' 
;

COMMENT ON COLUMN CRUISE.cruise_cost IS 'Cruise Cost per Person' 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT CRUISE_PK PRIMARY KEY ( cruise_id ) ;

CREATE TABLE CRUISE_PORT 
    ( 
     cruise_id      NUMBER (7)  NOT NULL , 
     port_code      NUMBER (7)  NOT NULL , 
     arr_dep_status VARCHAR2 (50)  NOT NULL , 
     date_and_time  DATE  NOT NULL 
    ) 
;

COMMENT ON COLUMN CRUISE_PORT.cruise_id IS 'Cruise ID' 
;

COMMENT ON COLUMN CRUISE_PORT.port_code IS 'Port Code' 
;

COMMENT ON COLUMN CRUISE_PORT.arr_dep_status IS 'Arrival or Departure status' 
;

COMMENT ON COLUMN CRUISE_PORT.date_and_time IS 'Date and Time of Arrival/Departure' 
;

ALTER TABLE CRUISE_PORT 
    ADD CONSTRAINT CRUISE_PORT_PK PRIMARY KEY ( cruise_id, date_and_time ) ;

CREATE TABLE OPERATOR 
    ( 
     oper_id   NUMBER (7)  NOT NULL , 
     oper_name VARCHAR2 (50)  NOT NULL , 
     oper_ceo  VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN OPERATOR.oper_id IS 'Operator ID' 
;

COMMENT ON COLUMN OPERATOR.oper_name IS 'Operator Name' 
;

COMMENT ON COLUMN OPERATOR.oper_ceo IS 'Name of operator''s Chief Executive Officer' 
;

ALTER TABLE OPERATOR 
    ADD CONSTRAINT OPERATOR_PK PRIMARY KEY ( oper_id ) ;

CREATE TABLE PASSENGER 
    ( 
     pas_id       NUMBER (7)  NOT NULL , 
     pas_fname    VARCHAR2 (50)  NOT NULL , 
     pas_lname    VARCHAR2 (50)  NOT NULL , 
     pas_gender   VARCHAR2 (50)  NOT NULL , 
     pas_dob      DATE  NOT NULL , 
     pas_street   VARCHAR2 (50)  NOT NULL , 
     pas_town     VARCHAR2 (50)  NOT NULL , 
     pas_postcode CHAR (10)  NOT NULL , 
     pas_country  VARCHAR2 (50)  NOT NULL , 
     pas_phone    CHAR (10)  NOT NULL , 
     pas_guardian NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PASSENGER.pas_id IS 'Passenger ID' 
;

COMMENT ON COLUMN PASSENGER.pas_fname IS 'Passenger First Name' 
;

COMMENT ON COLUMN PASSENGER.pas_lname IS 'Passenger Last Name' 
;

COMMENT ON COLUMN PASSENGER.pas_gender IS 'Passenger Gender' 
;

COMMENT ON COLUMN PASSENGER.pas_dob IS 'Passenger Date of Birth' 
;

COMMENT ON COLUMN PASSENGER.pas_street IS 'Passenger Street' 
;

COMMENT ON COLUMN PASSENGER.pas_town IS 'Passenger Town' 
;

COMMENT ON COLUMN PASSENGER.pas_postcode IS 'Passenger Postcode' 
;

COMMENT ON COLUMN PASSENGER.pas_country IS 'Passenger Country' 
;

COMMENT ON COLUMN PASSENGER.pas_guardian IS 'Passenger ID' 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT PASSENGER_PK PRIMARY KEY ( pas_id ) ;

CREATE TABLE PORT 
    ( 
     port_code    NUMBER (7)  NOT NULL , 
     port_name    VARCHAR2 (50)  NOT NULL , 
     port_ltd     NUMBER (7)  NOT NULL , 
     port_lgd     NUMBER (7)  NOT NULL , 
     country_code NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PORT.port_code IS 'Port Code' 
;

COMMENT ON COLUMN PORT.port_name IS 'Port Name' 
;

COMMENT ON COLUMN PORT.port_ltd IS 'Port Latitude' 
;

COMMENT ON COLUMN PORT.port_lgd IS 'Port Longitude' 
;

COMMENT ON COLUMN PORT.country_code IS 'Country Code' 
;

ALTER TABLE PORT 
    ADD CONSTRAINT PORT_PK PRIMARY KEY ( port_code ) ;

CREATE TABLE SHIP 
    ( 
     ship_code     NUMBER (7)  NOT NULL , 
     ship_name     VARCHAR2 (50)  NOT NULL , 
     ship_comdate  DATE  NOT NULL , 
     ship_tonnage  NUMBER (7)  NOT NULL , 
     ship_capacity NUMBER (7)  NOT NULL , 
     ship_country  VARCHAR2 (50)  NOT NULL , 
     oper_id       NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN SHIP.ship_code IS 'Ship Code' 
;

COMMENT ON COLUMN SHIP.ship_name IS 'Ship Name' 
;

COMMENT ON COLUMN SHIP.ship_comdate IS 'date of ship commisioned' 
;

COMMENT ON COLUMN SHIP.ship_tonnage IS 'Ship Tonnage' 
;

COMMENT ON COLUMN SHIP.ship_capacity IS 'Ship Guest Capacity' 
;

COMMENT ON COLUMN SHIP.ship_country IS 'Ship Country' 
;

COMMENT ON COLUMN SHIP.oper_id IS 'Operator ID' 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT OPERATOR_PKv1 PRIMARY KEY ( ship_code ) ;

ALTER TABLE BOOKING 
    ADD CONSTRAINT cabin_booking_fk FOREIGN KEY 
    ( 
     cabin_no,
     ship_code
    ) 
    REFERENCES CABIN 
    ( 
     cabin_no,
     ship_code
    ) 
;

ALTER TABLE PORT 
    ADD CONSTRAINT country_port_fk FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES COUNTRY 
    ( 
     country_code
    ) 
;

ALTER TABLE BOOKING 
    ADD CONSTRAINT cruise_booking_fk FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE CRUISE_PORT 
    ADD CONSTRAINT cruise_cruise_port_fk FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT operator_ship_fk FOREIGN KEY 
    ( 
     oper_id
    ) 
    REFERENCES OPERATOR 
    ( 
     oper_id
    ) 
;

ALTER TABLE BOOKING 
    ADD CONSTRAINT passenger_booking_fk FOREIGN KEY 
    ( 
     pas_id
    ) 
    REFERENCES PASSENGER 
    ( 
     pas_id
    ) 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT passenger_guardian_child FOREIGN KEY 
    ( 
     pas_guardian
    ) 
    REFERENCES PASSENGER 
    ( 
     pas_id
    ) 
;

ALTER TABLE CRUISE_PORT 
    ADD CONSTRAINT port_cruise_port_fk FOREIGN KEY 
    ( 
     port_code
    ) 
    REFERENCES PORT 
    ( 
     port_code
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT ship_cabin_fk FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT ship_cruise_fk FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             0
-- ALTER TABLE                             21
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SPOOL off
set echo off